name = "hex-bareiss-mathlib"
defaultTargets = ["HexBareissMathlib"]

[[require]]
name = "HexBasic"
git = "https://github.com/kim-em/hex-basic.git"
rev = "f1580d28c2e9ff9e8d4d7cdef9dccbaa17780b03"

[[require]]
name = "HexDeterminantMathlib"
git = "https://github.com/kim-em/hex-determinant-mathlib.git"
rev = "0d9134f3e416b868b90d3f770cbe9a02557bbd46"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.32.0-rc1-patch1"

[[lean_lib]]
name = "HexBareissMathlib"
